### ISSUE TITLE
Pasting Only Works with JSON

### ISSUE THREAD

**Issue by vistamix77** [haroldo-ok/bitsy-converter#15]
I'm trying to use the converter to convert games to LIBCV without success. Here are the steps:

Copy Bitsy code from Bitsy
Open Bitsy Converter
Select JSON
Paste Code
This works - I get my code converted to JSON

But I'm unable to select the other three options to convert the code after this. The tabs just flash but nothing changes.

Then I try
Reset Bitsy Converter
Select LIBCV in Bitsy Converter
Attempt to Paste Code (doesn't work)
Attempt to delete code in left hand side of converter (only able to delete a few lines)

I am testing this in the following browsers: (On the Mac) Safari, Chrome, Firefox. (On Windows 10) Default Windows Browser (edge)

Attached is the code for my game.
[welcome_to_enduro_death_race_tur.bitsy.zip](https://github.com/haroldo-ok/bitsy-converter/files/6136991/welcome_to_enduro_death_race_tur.bitsy.zip)

**Comment by haroldo-ok** [comment]
I can confirm that when converting this script on the production version of Bitsy Converter, it is causing the error "Uncaught TypeError: n.children is undefined":

```
Uncaught TypeError: n.children is undefined
    mn libcv.js:61
    _n libcv.js:69
    fn libcv.js:78
    fn libcv.js:78
    libcv libcv.js:143
    libcv libcv.js:647
    value App.js:62
    value App.js:76
    onChange App.js:135
    onClick Tab.js:127
    React 12
    unstable_runWithPriority scheduler.production.min.js:266
    React 3
libcv.js:61:42
    mn libcv.js:61
    _n libcv.js:69
    fn libcv.js:78
    map self-hosted:221
    fn libcv.js:78
    libcv libcv.js:143
    libcv libcv.js:647
    value App.js:62
    value App.js:76
    value self-hosted:1177
    onChange App.js:135
    onClick Tab.js:127
    React 12
    bind_applyFunctionN self-hosted:1375
    Pn self-hosted:1338
    unstable_runWithPriority scheduler.production.min.js:266
    React 3
    <anonymous> self-hosted:1281
```

I have to test it with the debug version, later.

**Comment by GhostDog98** [comment]
Is there any news on this being fixed? This leaves bitsy converter basically unusable for any other platform other than json, since you can't possibly expect people to type out their entire game data, which is often in excess of 100kb...

**Comment by haroldo-ok** [comment]
Okay, thanks; I had forgotten about that problem. I may try to fix this when I get some time.

**Comment by haroldo-ok** [comment]
Okay, fixed the bug. Now, @vistamix77 's example script is converting correctly.
